<?php

namespace App\Helpers\PrintService;

// @codingStandardsIgnoreLine
abstract class ProtocolCommand
{
    const PRINT_TEXT = "PRINT_TEXT";
    const PRINT_LOGO = "PRINT_LOGO";
    const PRINT_IMAGE = "PRINT_IMAGE";
    const PRINT_PRODUCTS_HEADER = "PRINT_PRODUCTS_HEADER";
    const PRINT_PRODUCTS = "PRINT_PRODUCTS";
    const PRINT_PRICE_SUMMARY = "PRINT_PRICE_SUMMARY";
    const PRINT_PAYMENT_METHOD = "PRINT_PAYMENT_METHOD";
    const ALIGN = "ALIGN";
    const PRINT_MODE = "PRINT_MODE";
    const CUT = "CUT";
    const PULSE = "PULSE";
    const FEED = "FEED";
    const PRINT_TEXT_JUSTIFY = "PRINT_TEXT_JUSTIFY";
    //cierre
    const PRINT_CASHIER_SUMMARY = "PRINT_CASHIER_SUMMARY";
    const PRINT_CASHIER_DETAILS = "PRINT_CASHIER_DETAILS";
    const PRINT_SALES_SUMMARY = "PRINT_SALES_SUMMARY";
    const PRINT_SALES_DETAILS = "PRINT_SALES_DETAILS";
    //Reporte X y Z
    const PRINT_XZ_HEADER = "PRINT_XZ_HEADER";
    const PRINT_XZ_SUMMARY = "PRINT_XZ_SUMMARY";
    const PRINT_XZ_PAYMENTS = "PRINT_XZ_PAYMENTS";
    const PRINT_XZ_STATS = "PRINT_XZ_STATS";
    const PRINT_XZ_CARD_DETAILS = "PRINT_XZ_CARD_DETAILS";
    const PRINT_XZ_EMPLOYEE_DETAILS = "PRINT_XZ_EMPLOYEE_DETAILS";
    const PRINT_XZ_TAXES_TYPES = "PRINT_XZ_TAXES_TYPES";
    const PRINT_XZ_RAPPI_DETAILS = "PRINT_XZ_RAPPI_DETAILS";
    const PRINT_XZ_EXPENSES = "PRINT_XZ_EXPENSES";
}