<?php

use App\Store;
use Carbon\Carbon;
use Illuminate\Database\Seeder;

class StoreConfigsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        foreach (Store::all() as $store) {
            $docLengths = '' . rand(8, 10) . ',' . rand(11, 13);
            $inventory = Store::where('company_id', $store->company_id)->where('id', '<>', $store->id)
            ->inRandomOrder()->first();
            DB::table('store_configs')->insert([
                'store_id' => $store->id,
                'show_taxes' => rand(1, 100) > 10 ? 1 : 0,
                'document_lengths' => rand(1, 100) > 25 ? $docLengths : '',
                'uses_print_service' => 0,
                'employee_digital_comanda' => 0,
                'show_invoice_specs' => 0,
                'alternate_bill_sequence' => 0,
                'comanda' => "[{\"cmd\":\"PRINT_LOGO\",\"payload\":{\"from_integration\":true}},{\"cmd\":\"PRINT_MODE\",\"payload\":{\"mode\":\"DOUBLE_HEIGHT\"}},{\"cmd\":\"PRINT_TEXT\",\"payload\":{\"text\":\"Fecha: %s\",\"tokens\":[\"order_created_at\"]}},{\"cmd\":\"PRINT_TEXT\",\"payload\":{\"text\":\"%s\",\"tokens\":[\"spot_name\"]}},{\"cmd\":\"PRINT_TEXT\",\"payload\":{\"text\":\"%s\",\"tokens\":[\"employee_name\"]}},{\"cmd\":\"PRINT_TEXT\",\"payload\":{\"from_integration\":true,\"text\":\"Cliente: %s\",\"tokens\":[\"customer_name\"]}},{\"cmd\":\"PRINT_TEXT\",\"payload\":{\"from_integration\":true,\"text\":\"Orden %s: %s\",\"tokens\":[\"integration_name\",\"order_number\"]}},{\"cmd\":\"PRINT_PRODUCTS_HEADER\",\"payload\":{\"show_reprint\":true,\"show_header_row\":false}},{\"cmd\":\"PRINT_PRODUCTS\",\"payload\":{\"is_food_service\":false,\"show_instructions\":true,\"products_alignment\":\"LEFT\",\"instructions_alignment\":\"RIGHT\"}},{\"cmd\":\"FEED\",\"payload\":{\"lines\":2}},{\"cmd\":\"CUT\",\"payload\":{\"mode\":\"FULL\"}}]",
                'precuenta' => "[{\"cmd\":\"ALIGN\",\"payload\":{\"alignment\":\"CENTER\"}},{\"cmd\":\"PRINT_TEXT\",\"payload\":{\"text\":\"********* PRE-CUENTA *********\"}},{\"cmd\":\"ALIGN\",\"payload\":{\"alignment\":\"LEFT\"}},{\"cmd\":\"PRINT_TEXT\",\"payload\":{\"text\":\"%s\",\"tokens\":[\"store_name\"]}},{\"cmd\":\"PRINT_TEXT\",\"payload\":{\"text\":\"Fecha: %s\",\"tokens\":[\"order_created_at\"]}},{\"cmd\":\"PRINT_TEXT\",\"payload\":{\"text\":\"%s\",\"tokens\":[\"spot_name\"]}},{\"cmd\":\"PRINT_TEXT\",\"payload\":{\"text\":\"%s\",\"tokens\":[\"employee_name\"]}},{\"cmd\":\"PRINT_PRODUCTS_HEADER\",\"payload\":{\"show_reprint\":false,\"show_header_row\":true}},{\"cmd\":\"PRINT_PRODUCTS\",\"payload\":{\"is_food_service\":false,\"show_instructions\":true}},{\"cmd\":\"ALIGN\",\"payload\":{\"alignment\":\"CENTER\"}},{\"cmd\":\"PRINT_TEXT\",\"payload\":{\"text\":\"------------------------------------\"}},{\"cmd\":\"ALIGN\",\"payload\":{\"alignment\":\"RIGHT\"}},{\"cmd\":\"PRINT_PRICE_SUMMARY\",\"payload\":{\"text\":\"\"}},{\"cmd\":\"PRINT_DISCOUNT\",\"payload\":{\"text\":\"------------------------------------\"}},{\"cmd\":\"PRINT_SUBTOTAL_DISCOUNTED\",\"payload\":{\"text\":\"------------------------------------\"}},{\"cmd\":\"PRINT_TAXES\",\"payload\":{\"text\":\"------------------------------------\"}},{\"cmd\":\"PRINT_TOTAL\",\"payload\":{\"text\":\"------------------------------------\"}},{\"cmd\":\"PRINT_TIP\",\"payload\":{\"text\":\"------------------------------------\"}},{\"cmd\":\"PRINT_TOTAL_PLUS_TIPS\",\"payload\":{\"text\":\"------------------------------------\"}},{\"cmd\":\"ALIGN\",\"payload\":{\"alignment\":\"CENTER\"}},{\"cmd\":\"PRINT_TEXT\",\"payload\":{\"text\":\"****** DATOS DEL CLIENTE ******\"}},{\"cmd\":\"ALIGN\",\"payload\":{\"alignment\":\"LEFT\"}},{\"cmd\":\"FEED\",\"payload\":{\"lines\":1}},{\"cmd\":\"PRINT_TEXT\",\"payload\":{\"text\":\"APELLIDOS ____________________\"}},{\"cmd\":\"FEED\",\"payload\":{\"lines\":1}},{\"cmd\":\"PRINT_TEXT\",\"payload\":{\"text\":\"NOMBRES ______________________\"}},{\"cmd\":\"FEED\",\"payload\":{\"lines\":1}},{\"cmd\":\"PRINT_TEXT\",\"payload\":{\"text\":\"DIRECCION ____________________\"}},{\"cmd\":\"FEED\",\"payload\":{\"lines\":1}},{\"cmd\":\"PRINT_TEXT\",\"payload\":{\"text\":\"______________________________\"}},{\"cmd\":\"FEED\",\"payload\":{\"lines\":1}},{\"cmd\":\"PRINT_TEXT\",\"payload\":{\"text\":\"RUC __________________________\"}},{\"cmd\":\"FEED\",\"payload\":{\"lines\":1}},{\"cmd\":\"PRINT_TEXT\",\"payload\":{\"text\":\"TELEFONO _____________________\"}},{\"cmd\":\"FEED\",\"payload\":{\"lines\":1}},{\"cmd\":\"PRINT_TEXT\",\"payload\":{\"text\":\"E-MAIL _______________________\"}},{\"cmd\":\"FEED\",\"payload\":{\"lines\":1}},{\"cmd\":\"ALIGN\",\"payload\":{\"alignment\":\"RIGHT\"}},{\"cmd\":\"PRINT_TEXT\",\"payload\":{\"text\":\"PROPINA ________________\"}},{\"cmd\":\"CUT\",\"payload\":{\"mode\":\"FULL\"}}]",
                'factura' => "[{\"cmd\":\"PRINT_LOGO\",\"payload\":{\"from_integration\":false}},{\"cmd\":\"PRINT_TEXT\",\"payload\":{\"text\":\"Fecha: %s\",\"tokens\":[\"invoice_created_at\"]}},{\"cmd\":\"PRINT_TEXT\",\"payload\":{\"text\":\"Cédula/RUC: %s\",\"tokens\":[\"invoice_document\"]}},{\"cmd\":\"PRINT_TEXT\",\"payload\":{\"text\":\"Nombre: %s\",\"tokens\":[\"invoice_name\"]}},{\"cmd\":\"PRINT_TEXT\",\"payload\":{\"text\":\"Dirección: %s\",\"tokens\":[\"invoice_address\"]}},{\"cmd\":\"PRINT_TEXT\",\"payload\":{\"text\":\"Teléfono: %s\",\"tokens\":[\"invoice_phone\"]}},{\"cmd\":\"PRINT_TEXT\",\"payload\":{\"text\":\"E-mail: %s\",\"tokens\":[\"invoice_email\"]}},{\"cmd\":\"PRINT_TEXT\",\"payload\":{\"text\":\"Mesero: %s\",\"tokens\":[\"order_employee_name\"]}},{\"cmd\":\"PRINT_TEXT\",\"payload\":{\"text\":\"Factura #%s\",\"tokens\":[\"official_invoice_number\"]}},{\"cmd\":\"PRINT_TEXT\",\"payload\":{\"text\":\"%s\",\"tokens\":[\"spot_name\"]}},{\"cmd\":\"PRINT_PRODUCTS_HEADER\",\"payload\":{\"show_reprint\":false,\"show_header_row\":true}},{\"cmd\":\"PRINT_PRODUCTS\",\"payload\":{\"is_food_service\":false,\"show_instructions\":true}},{\"cmd\":\"ALIGN\",\"payload\":{\"alignment\":\"CENTER\"}},{\"cmd\":\"PRINT_TEXT\",\"payload\":{\"text\":\"------------------------------------\"}},{\"cmd\":\"ALIGN\",\"payload\":{\"alignment\":\"RIGHT\"}},{\"cmd\":\"PRINT_PRICE_SUMMARY\",\"payload\":{\"text\":\"\"}},{\"cmd\":\"ALIGN\",\"payload\":{\"alignment\":\"CENTER\"}},{\"cmd\":\"FEED\",\"payload\":{\"lines\":1}},{\"cmd\":\"PRINT_PAYMENT_METHOD\",\"payload\":{\"text\":\"\"}},{\"cmd\":\"PRINT_TEXT\",\"payload\":{\"text\":\"%s\",\"tokens\":[\"billing_code_resolution\"]}},{\"cmd\":\"FEED\",\"payload\":{\"lines\":1}},{\"cmd\":\"PRINT_TEXT\",\"payload\":{\"text\":\"%s\",\"tokens\":[\"tax_billing_description\"]}},{\"cmd\":\"FEED\",\"payload\":{\"lines\":2}},{\"cmd\":\"CUT\",\"payload\":{\"mode\":\"FULL\"}},{\"cmd\":\"PULSE\",\"payload\":{\"mode\":\"\"}}]",
                "cierre" => '[{"cmd":"PRINT_CASHIER_SUMMARY","payload":{"text":""}},{"cmd":"ALIGN","payload":{"alignment":"CENTER"}},{"cmd":"PRINT_TEXT","payload":{"text":"-----------------------------------"}},{"cmd":"PRINT_SALES_SUMMARY","payload":{"text":""}},{"cmd":"ALIGN","payload":{"alignment":"CENTER"}},{"cmd":"PRINT_TEXT","payload":{"text":"-----------------------------------"}},{"cmd":"PRINT_TEXT","payload":{"text":"Detalle de Ventas"}},{"cmd":"PRINT_TEXT","payload":{"text":"-----------------------------------"}},{"cmd":"ALIGN","payload":{"alignment":"LEFT"}},{"cmd":"PRINT_SALES_DETAILS","payload":{"text":""}},{"cmd":"ALIGN","payload":{"alignment":"CENTER"}},{"cmd":"PRINT_TEXT","payload":{"text":"-----------------------------------"}},{"cmd":"PRINT_TEXT","payload":{"text":"Detalle de Caja"}},{"cmd":"PRINT_TEXT","payload":{"text":"-----------------------------------"}},{"cmd":"PRINT_CASHIER_DETAILS","payload":{"text":""}},{"cmd":"FEED","payload":{"lines":2}},{"cmd":"CUT","payload":{"mode":"FULL"}}]',
                'inventory_store_id' => (rand(1, 10) > 7 && $inventory) ? $inventory->id : null,
                "xz_format" => '[{"cmd": "PRINT_XZ_HEADER", "payload": {"text": ""}}, {"cmd": "ALIGN", "payload": {"alignment": "CENTER"}}, {"cmd": "FEED", "payload": {"lines": 1}}, {"cmd": "PRINT_TEXT", "payload": {"text": "-----------------------------------"}}, {"cmd": "FEED", "payload": {"lines": 1}}, {"cmd": "ALIGN", "payload": {"alignment": "LEFT"}}, {"cmd": "PRINT_XZ_SUMMARY", "payload": {"text": ""}}, {"cmd": "ALIGN", "payload": {"alignment": "CENTER"}}, {"cmd": "FEED", "payload": {"lines": 1}}, {"cmd": "PRINT_TEXT", "payload": {"text": "-----------------------------------"}}, {"cmd": "FEED", "payload": {"lines": 1}}, {"cmd": "ALIGN", "payload": {"alignment": "LEFT"}}, {"cmd": "PRINT_XZ_PAYMENTS", "payload": {"text": ""}}, {"cmd": "ALIGN", "payload": {"alignment": "CENTER"}}, {"cmd": "FEED", "payload": {"lines": 1}}, {"cmd": "PRINT_TEXT", "payload": {"text": "-----------------------------------"}}, {"cmd": "FEED", "payload": {"lines": 1}}, {"cmd": "ALIGN", "payload": {"alignment": "LEFT"}}, {"cmd": "PRINT_XZ_STATS", "payload": {"text": ""}}, {"cmd": "ALIGN", "payload": {"alignment": "CENTER"}}, {"cmd": "FEED", "payload": {"lines": 1}}, {"cmd": "PRINT_TEXT", "payload": {"text": "-----------------------------------"}}, {"cmd": "FEED", "payload": {"lines": 1}}, {"cmd": "ALIGN", "payload": {"alignment": "LEFT"}}, {"cmd": "PRINT_XZ_TAXES_TYPES", "payload": {"text": ""}}, {"cmd": "ALIGN", "payload": {"alignment": "CENTER"}}, {"cmd": "FEED", "payload": {"lines": 1}}, {"cmd": "PRINT_TEXT", "payload": {"text": "-----------------------------------"}}, {"cmd": "FEED", "payload": {"lines": 1}}, {"cmd": "ALIGN", "payload": {"alignment": "LEFT"}}, {"cmd": "PRINT_XZ_CARD_DETAILS", "payload": {"text": ""}}, {"cmd": "ALIGN", "payload": {"alignment": "CENTER"}}, {"cmd": "FEED", "payload": {"lines": 1}}, {"cmd": "PRINT_TEXT", "payload": {"text": "-----------------------------------"}}, {"cmd": "FEED", "payload": {"lines": 1}}, {"cmd": "ALIGN", "payload": {"alignment": "LEFT"}}, {"cmd": "PRINT_XZ_EMPLOYEE_DETAILS", "payload": {"text": ""}}, {"cmd": "ALIGN", "payload": {"alignment": "CENTER"}}, {"cmd": "FEED", "payload": {"lines": 1}}, {"cmd": "PRINT_TEXT", "payload": {"text": "-----------------------------------"}}, {"cmd": "FEED", "payload": {"lines": 1}}, {"cmd": "ALIGN", "payload": {"alignment": "LEFT"}}, {"cmd": "PRINT_XZ_RAPPI_DETAILS", "payload": {"text": ""}}, {"cmd": "CUT", "payload": {"mode": "FULL"}}]',
                "credit_format" => '[{"cmd": "ALIGN", "payload": {"alignment": "CENTER"}}, {"cmd": "PRINT_TEXT", "payload": {"text": "%s", "tokens": ["store_name"]}}, {"cmd": "ALIGN", "payload": {"alignment": "LEFT"}}, {"cmd": "PRINT_TEXT", "payload": {"text": "Fecha: %s", "tokens": ["invoice_created_at"]}}, {"cmd": "PRINT_TEXT", "payload": {"text": "Cédula/RUC: %s", "tokens": ["invoice_document"]}}, {"cmd": "PRINT_TEXT", "payload": {"text": "Nombre: %s", "tokens": ["invoice_name"]}}, {"cmd": "PRINT_TEXT", "payload": {"text": "Cliente: %s", "tokens": ["customer_name"], "from_integration": true}}, {"cmd": "PRINT_TEXT", "payload": {"text": "Dirección: %s", "tokens": ["invoice_address"]}}, {"cmd": "PRINT_TEXT", "payload": {"text": "Teléfono: %s", "tokens": ["invoice_phone"]}}, {"cmd": "PRINT_TEXT", "payload": {"text": "E-mail: %s", "tokens": ["invoice_email"]}}, {"cmd": "PRINT_TEXT", "payload": {"text": "Mesero: %s", "tokens": ["order_employee_name"]}}, {"cmd": "PRINT_TEXT", "payload": {"text": "Nota de Crédito #%s", "tokens": ["credit_note_number"]}}, {"cmd": "PRINT_TEXT", "payload": {"text": "%s", "tokens": ["spot_name"]}}, {"cmd": "PRINT_TEXT", "payload": {"text": "Orden %s: %s", "tokens": ["integration_name", "order_number"], "from_integration": true}}, {"cmd": "PRINT_PRODUCTS_HEADER", "payload": {"show_reprint": false, "show_header_row": true}}, {"cmd": "PRINT_PRODUCTS", "payload": {"is_food_service": false, "show_instructions": true}}, {"cmd": "ALIGN", "payload": {"alignment": "CENTER"}}, {"cmd": "PRINT_TEXT", "payload": {"text": "------------------------------------"}}, {"cmd": "ALIGN", "payload": {"alignment": "RIGHT"}}, {"cmd": "PRINT_PRICE_SUMMARY", "payload": {"text": ""}}, {"cmd": "ALIGN", "payload": {"alignment": "CENTER"}}, {"cmd": "FEED", "payload": {"lines": 1}}, {"cmd": "PRINT_PAYMENT_METHOD", "payload": {"text": ""}}, {"cmd": "PRINT_TEXT", "payload": {"text": "%s", "tokens": ["billing_code_resolution"]}}, {"cmd": "FEED", "payload": {"lines": 1}}, {"cmd": "PRINT_TEXT", "payload": {"text": "%s", "tokens": ["tax_billing_description"]}}, {"cmd": "ALIGN", "payload": {"alignment": "CENTER"}}, {"cmd": "PRINT_TEXT", "payload": {"text": "------------------------------------"}}, {"cmd": "ALIGN", "payload": {"alignment": "LEFT"}}, {"cmd": "FEED", "payload": {"lines": 2}}, {"cmd": "CUT", "payload": {"mode": "FULL"}}, {"cmd": "PULSE", "payload": {"mode": ""}}]',
                'created_at' => Carbon::now()->toDateTimeString(),
                'updated_at' => Carbon::now()->toDateTimeString(),
            ]);
        }
    }
}
